/* 
 * Copyright 2015 Alexander Nozik.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package hep.dataforge.workspace.identity;

import hep.dataforge.meta.Meta;
import hep.dataforge.meta.MetaBuilder;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Objects;

/**
 * The identity for classes. Uses reflection to ensure the same version of
 * generated bytecode is used.
 *
 * @author Alexander Nozik
 */
public class ClassIdentity implements Identity {

    private Class cl;
    private String md5;

    public ClassIdentity(Class cl) {
        this.cl = cl;
        File classFile = new File(cl.getResource(cl.getCanonicalName()).getFile());
        try {
            this.md5 = new String(MessageDigest.getInstance("MD5").digest(Files.readAllBytes(classFile.toPath())));
        } catch (NoSuchAlgorithmException ex) {
            throw new Error();
        } catch (IOException ex) {
            throw new RuntimeException("Class not found", ex);
        }
    }

    @Override
    public int hashCode() {
        int hash = 3 + md5.hashCode();
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final ClassIdentity other = (ClassIdentity) obj;
        return Objects.equals(this.md5, other.md5);
    }

    @Override
    public String toString() {
        return "class::" + md5;
    }

    @Override
    public Meta toMeta() {
        return new MetaBuilder("id")
                .setValue("type","class")
                .setValue("class", cl.getName())
                .setValue("md5", md5);
    }

    @Override
    public void fromMeta(Meta meta) {
        try {
            this.cl = Class.forName(meta.getString("class"));
        } catch (ClassNotFoundException e) {
            LoggerFactory.getLogger(getClass()).warn("Can't find class described in class identity");
        }
        this.md5 = meta.getString("md5");
    }
}
